[package]
name = "makepad-example-fractal-zoom"
version = "0.1.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad fractal zoom example"
license = "MIT OR Apache-2.0"
metadata.makepad-auto-version = "x"

[dependencies]
makepad-component = {path="../../component", version="0.1.0"}

[features]
nightly = ["makepad-component/nightly"]

