[package]
name = "editor_example_wasm"
version = "0.1.0"
authors = ["makepaddev"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]

[dependencies.makepad-render]
path="../../../render"

[dependencies.editor_example_app]
path="../app"

