[package]
name = "layout_example"
version = "0.1.0"
authors = ["makepaddev"]
edition = "2018"

[dependencies]

[dependencies.makepad-component]
path="../../component"
version="0.1"

[features]
nightly = ["makepad-component/nightly"]

