[package]
name = "makepad_wasm"
version = "0.1.0"
authors = ["arc"]
edition = "2018"

[lib]
path = "../src/main.rs"
crate-type = ["cdylib"]

[dependencies]
ron = "0.5"
serde = { version = "1.0", features = ["derive"] }

[dependencies.makepad-widget]
path="../../widget"

[dependencies.makepad-render]
path="../../render"

[dependencies.makepad-hub]
path="../hub"
