[package]
name = "mace"
version = "0.1.0"
authors = ["Eddy Bruel <ejpbruel@gmail.com>"]
edition = "2018"

[dependencies]
bincode = "1.3"
makepad-render = { path = "../render" }
makepad-widget = { path = "../widget" }
serde = { version = "1.0", features = ["derive"] }