[package]
name = "makepad-wasm-msg"
version = "0.1.0"
authors = ["Eddy Bruel <ejpbruel@gmail.com>"]
edition = "2018"

[dependencies]
makepad-derive-wasm-msg = { path = "./derive_wasm_msg", version = "0.1" }
makepad-live-id = { path = "../live_id", version = "0.1" }
