[workspace]

members = [
    "makepad",
    "makepad/wasm", 
    "examples/audio_example",
    "examples/bare_example",
    "examples/widget_example",
    "examples/cmdline_example",
    "workshops/nov28_step1_wasm", 
    "workspace"
]
 