[workspace]

members = [
    "code_editor/text_segmentation",
    "code_editor/ucd",
    "examples/bare_example", 
    "examples/layout_example", 
    "examples/cmdline_example",
    "examples/wasm_example",
    "examples/fun_audio",
    "studio",
    "tools/webserver",
]

[profile.release]
#lto=true
#codegen-units=1
#panic = 'abort'
#opt-level = 'z'
