[workspace]

members = [
    "makepad",
    "makepad/wasm", 
    "examples/bare_example", 
    "examples/bare_example/wasm",
    "examples/widget_example",
    "examples/cmdline_example",
    "tools/webserver",
    "tools/brotli_test",
    "builder"
]

[profile.release]
#lto=true
 
