[workspace]

members = [
    "code_editor/btree",
    "code_editor/segment",
    "code_editor/ucd",
    "examples/bare_example", 
    "examples/layout_example", 
    "examples/cmdline_example",
    "platform/wasm_bridge/test",
    "examples/fun_audio",
    "studio",
    "tools/webserver",
    "tools/brotli_check",
]

[profile.release]
#lto=true
#codegen-units=1
#panic = 'abort'
#opt-level = 'z'
