workspace.exclude = [
    "code_editor/regex",
    "code_editor/range_set",
    "code_editor/rope",
    "code_editor/segment",
    "code_editor/regex",
    "code_editor/ucd",
    "code_editor/varint"
]

workspace.members = [
    "examples/numbers", 
    "examples/fractal_zoom", 
    "examples/cmdline_example",
    "examples/ironfish",
    "examples/simple",
    "examples/touch",
    "examples/teamtalk",
    "examples/video_mixer",
    "libs/wasm_bridge/test",
    "studio",
    "tools/windows_strip",
    "tools/auto_version",
    "tools/web_server", 
    "tools/file_router",
    "tools/wasm_strip",
]



