[package]
name = "cmdline_example"
version = "0.1.0"
edition = "2018"

[dependencies]
makepad-error-log = {path="../../libs/error_log", version="0.1"}
makepad-miniz = {path="../../libs/miniz", version="0.1"}
base64 = {version="0.13"}
[features]
nightly = ["makepad-error-log/nightly"]
