[package]
name = "cmdline_example"
version = "0.1.0"
edition = "2018"

[dependencies.makepad-live-compiler]
path="../../render/live_compiler"
version="0.1"

[dependencies.makepad-shader-compiler]
path="../../render/shader_compiler"
version="0.1" 

