[package]
name = "makepad-objc-sys"
version = "0.3.0"
authors = ["Makepad <info@makepad.nl>", "Steven Sheldon"]
description = "Makepad fork of SSheldon/rust-objc without libc dep."
keywords = ["objective-c", "osx", "ios", "cocoa", "uikit"]
license = "MIT"
repository = "http://github.com/SSheldon/rust-objc"
metadata.makepad-auto-version = "Fv-kCjCEQuT49weirwOogmiIXzI="
