[package]
name = "makepad-geometry"
version = "0.1.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad 2d geometry tools"
license = "MIT OR Apache-2.0"
metadata.makepad-auto-version = "x"

[dependencies]
makepad-internal-iter = { path = "../internal_iter", version = "0.1" }
