[package]
name = "makepad-example-shader"
version = "0.1.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad shader example"
license = "MIT OR Apache-2.0"
metadata.makepad-auto-version = "_PRHHekkxowgpmC6S7hS630bxt8="

[dependencies]
makepad-widgets = { path = "../../widgets", version = "0.1.0" }
 
[features]
nightly = ["makepad-widgets/nightly"]

