[package]
name = "makepad-shader-ast-impl"
version = "0.1.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad shader AST implementation"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.2"
proc-macro-hack = "*"
proc-macro2 = "1.0.1"

[dependencies.syn]
version = "1.0.4"
features = ["full"]
