[package]
name = "makepad-live-parser"
version = "0.1.0"
authors = ["Eddy Bruel <ejpbruel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
makepad-live-derive = { path = "./live_derive", version = "0.1" }
makepad-microserde = { path = "../microserde", version = "0.1" }
