[package]
name = "bare_example"
version = "0.1.0"
authors = ["makepaddev"]
edition = "2018"

[dependencies]

[dependencies.makepad-render]
path="../../render"
version="0.2"

[dependencies.makepad-widget]
path="../../widget"
version="0.1"