[package]
name = "makepad-media"
version = "0.1.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad Media"
license = "MIT"

[dependencies]
makepad-platform = { path = "../platform", version = "0.1" }

[features] 
nightly = ["makepad-platform/nightly"]

