[package]
name = "makepad-derive-live"
version = "0.3.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad platform live DSL derive macros"
license = "MIT OR Apache-2.0"
metadata.makepad-auto-version = "xfXJEt-VjsFMotX6nxPX32MUQ3w="

[lib]
proc-macro = true

[dependencies]
makepad-micro-proc-macro = { path = "../../libs/micro_proc_macro", version = "0.3.0" }
makepad-live-id = { path = "../../libs/live_id", version = "0.3.0" }

[features]
nightly = []
