[package]
name = "makepad-trapezoidator"
version = "0.1.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Polygon trapezoidator"
license = "MIT OR Apache-2.0"
metadata.makepad-auto-version = "x"

[dependencies]
makepad-geometry = { path = "../geometry", version = "0.1.0" }
makepad-internal-iter = { path = "../internal_iter", version = "0.1.0" }
makepad-path = { path = "../path", version = "0.1.0" }
