[package]
name = "makepad-ttf-parser"
version = "0.3.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "TTF parser"
license = "MIT OR Apache-2.0"
metadata.makepad-auto-version = "2tGPW2xsMM9xTRggUjvTRU_3trc="

[dependencies]
makepad-font = { path = "../font", version = "0.3.0" }
makepad-geometry = { path = "../geometry", version = "0.3.0" }
makepad-internal-iter = { path = "../internal_iter", version = "0.3.0" }
