[package]
name = "makepad-web-server"
version = "0.1.0"
edition = "2018"

[dependencies]
makepad-http = { path = "http", version = "0.1" }
makepad-collab-server = {path = "../../studio/collab_server", version = "0.1"}
 
[features]
nightly=[]