[package]
name = "makepad-studio"
version = "0.1.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad studio"
license = "MIT OR Apache-2.0"
metadata.makepad-auto-version = "riUDqcjTALHACoZcWI84ujtQpi0="

[dependencies]
makepad-widgets = {path="../widgets" , version="0.1.0"}
makepad-editor-core = {path="./editor_core", version="0.1.0"}
makepad-collab-protocol = {path="./collab_protocol", version="0.1.0"}
makepad-collab-server = {path="./collab_server", version="0.1.0"}

[features]
nightly = ["makepad-widgets/nightly"]

