[package]
name = "makepad-image-formats"
version = "0.1.0"
authors = ["Desmond Germans <desmond@germansmedia.nl>"]
edition = "2018"
description = "Makepad image formats"
license = "MIT OR Apache-2.0"
metadata.makepad-auto-version = "x"

[features]
nightly = []
