[package]
name = "makepad-collab-protocol"
version = "0.1.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad collab protocol"
license = "MIT"

[dependencies]
makepad-live-id = { path = "../../libs/live_id", version = "0.1"}
makepad-micro-serde = {path = "../../libs/micro_serde", version = "0.1"}
makepad-editor-core = {path="../editor_core", version="0.1"}

