[package]
name = "makepad-example-numbers"
version = "0.1.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad numbers example"
license = "MIT OR Apache-2.0"
metadata.makepad-auto-version = "DgrOnLN-Md60p06NyrswctujVm0="

[dependencies]
makepad-component = { path = "../../component", version = "0.1.0" }
 
[features]
nightly = ["makepad-component/nightly"]

