[package]
name = "makepad-internal-iter"
version = "0.3.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Internal iterators"
license = "MIT OR Apache-2.0"
metadata.makepad-auto-version = "IRYPDN81OrWG4pc7_lRsqzU5XKU="

[dependencies]
