[package]
name = "ttf_parser"
version = "0.1.0"
authors = ["Eddy Bruel <ejpbruel@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
font = { path = "../font" }
makepad-geometry = { path = "../geometry" }
makepad-internal-iter = { path = "../internal_iter" }
