[package]
name = "makepad-example-simple"
version = "0.3.0"
authors = ["Makepad <info@makepad.nl>"]
edition = "2018"
description = "Makepad simple example"
license = "MIT OR Apache-2.0"
metadata.makepad-auto-version = "7YdS6q28Cdrfzv-t4CYwh1JEYZk="

[dependencies]
makepad-widgets = { path = "../../widgets", version = "0.3.0" }
 
[features]
nightly = ["makepad-widgets/nightly"]

